// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_platform.Data;

namespace web_platform.Migrations
{
    [DbContext(typeof(UmbracoDbContext))]
    [Migration("20201123115420_UpdateSeedData1")]
    partial class UpdateSeedData1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("web_platform.Models.CMSComponentVersion", b =>
                {
                    b.Property<int>("CMSComponentVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("CMSComponentVersionId");

                    b.ToTable("CMSComponentVersion");

                    b.HasData(
                        new
                        {
                            CMSComponentVersionId = 1
                        },
                        new
                        {
                            CMSComponentVersionId = 2
                        });
                });

            modelBuilder.Entity("web_platform.Models.SecurityIssuePost", b =>
                {
                    b.Property<int>("SecurityIssuePostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CMSComponentVersionId")
                        .HasColumnType("int");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueReproduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecurityIssuePostId");

                    b.HasIndex("CMSComponentVersionId");

                    b.ToTable("SecurityIssuePost");
                });

            modelBuilder.Entity("web_platform.Models.CMSComponentVersion", b =>
                {
                    b.OwnsOne("web_platform.Models.CMSComponent", "CMSComponent", b1 =>
                        {
                            b1.Property<int>("CMSComponentVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CMSComponentVersionId");

                            b1.ToTable("CMSComponents");

                            b1.WithOwner()
                                .HasForeignKey("CMSComponentVersionId");

                            b1.HasData(
                                new
                                {
                                    CMSComponentVersionId = 1,
                                    Name = "Umbraco CMS"
                                },
                                new
                                {
                                    CMSComponentVersionId = 2,
                                    Name = "Umbraco CMS"
                                });
                        });

                    b.OwnsOne("web_platform.Models.Version", "Version", b1 =>
                        {
                            b1.Property<string>("VersionNumber")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("CMSComponentVersionId")
                                .HasColumnType("int");

                            b1.HasKey("VersionNumber");

                            b1.HasIndex("CMSComponentVersionId")
                                .IsUnique();

                            b1.ToTable("Versions");

                            b1.WithOwner()
                                .HasForeignKey("CMSComponentVersionId");

                            b1.HasData(
                                new
                                {
                                    VersionNumber = "1.1",
                                    CMSComponentVersionId = 1
                                },
                                new
                                {
                                    VersionNumber = "1.2",
                                    CMSComponentVersionId = 2
                                });
                        });

                    b.Navigation("CMSComponent");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("web_platform.Models.SecurityIssuePost", b =>
                {
                    b.HasOne("web_platform.Models.CMSComponentVersion", "CMSComponentVersion")
                        .WithMany()
                        .HasForeignKey("CMSComponentVersionId");

                    b.Navigation("CMSComponentVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
