// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_platform.Data;

namespace web_platform.Migrations
{
    [DbContext(typeof(UmbracoDbContext))]
    partial class UmbracoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("web_platform.Models.CMSComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CMSComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CType = 1,
                            Name = "Forms"
                        },
                        new
                        {
                            Id = 2,
                            CType = 1,
                            Name = "uSync"
                        },
                        new
                        {
                            Id = 3,
                            CType = 0,
                            Name = "Umbraco UNO"
                        },
                        new
                        {
                            Id = 4,
                            CType = 0,
                            Name = "Umbraco Cloud"
                        },
                        new
                        {
                            Id = 5,
                            CType = 0,
                            Name = "Umbraco Hearthbreak"
                        },
                        new
                        {
                            Id = 6,
                            CType = 0,
                            Name = "Umbraco CMS"
                        });
                });

            modelBuilder.Entity("web_platform.Models.CMSComponentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CMSComponentId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CMSComponentId");

                    b.HasIndex("ComponentVersionId");

                    b.ToTable("CMSComponentVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CMSComponentId = 3,
                            ComponentVersionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CMSComponentId = 3,
                            ComponentVersionId = 3
                        },
                        new
                        {
                            Id = 3,
                            CMSComponentId = 3,
                            ComponentVersionId = 5
                        },
                        new
                        {
                            Id = 4,
                            CMSComponentId = 3,
                            ComponentVersionId = 8
                        },
                        new
                        {
                            Id = 5,
                            CMSComponentId = 4,
                            ComponentVersionId = 2
                        },
                        new
                        {
                            Id = 6,
                            CMSComponentId = 4,
                            ComponentVersionId = 6
                        },
                        new
                        {
                            Id = 7,
                            CMSComponentId = 4,
                            ComponentVersionId = 10
                        },
                        new
                        {
                            Id = 8,
                            CMSComponentId = 5,
                            ComponentVersionId = 3
                        },
                        new
                        {
                            Id = 9,
                            CMSComponentId = 5,
                            ComponentVersionId = 7
                        },
                        new
                        {
                            Id = 10,
                            CMSComponentId = 5,
                            ComponentVersionId = 11
                        },
                        new
                        {
                            Id = 11,
                            CMSComponentId = 5,
                            ComponentVersionId = 12
                        },
                        new
                        {
                            Id = 12,
                            CMSComponentId = 6,
                            ComponentVersionId = 3
                        },
                        new
                        {
                            Id = 13,
                            CMSComponentId = 6,
                            ComponentVersionId = 7
                        },
                        new
                        {
                            Id = 14,
                            CMSComponentId = 6,
                            ComponentVersionId = 9
                        },
                        new
                        {
                            Id = 15,
                            CMSComponentId = 1,
                            ComponentVersionId = 1
                        },
                        new
                        {
                            Id = 16,
                            CMSComponentId = 1,
                            ComponentVersionId = 2
                        },
                        new
                        {
                            Id = 17,
                            CMSComponentId = 1,
                            ComponentVersionId = 11
                        },
                        new
                        {
                            Id = 18,
                            CMSComponentId = 1,
                            ComponentVersionId = 12
                        },
                        new
                        {
                            Id = 19,
                            CMSComponentId = 2,
                            ComponentVersionId = 1
                        },
                        new
                        {
                            Id = 20,
                            CMSComponentId = 2,
                            ComponentVersionId = 4
                        },
                        new
                        {
                            Id = 21,
                            CMSComponentId = 2,
                            ComponentVersionId = 6
                        },
                        new
                        {
                            Id = 22,
                            CMSComponentId = 2,
                            ComponentVersionId = 11
                        });
                });

            modelBuilder.Entity("web_platform.Models.ComponentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("VersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentVersions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VersionNumber = "1.1"
                        },
                        new
                        {
                            Id = 2,
                            VersionNumber = "1.2"
                        },
                        new
                        {
                            Id = 3,
                            VersionNumber = "1.3"
                        },
                        new
                        {
                            Id = 4,
                            VersionNumber = "1.4"
                        },
                        new
                        {
                            Id = 5,
                            VersionNumber = "2.1"
                        },
                        new
                        {
                            Id = 6,
                            VersionNumber = "2.2"
                        },
                        new
                        {
                            Id = 7,
                            VersionNumber = "2.3"
                        },
                        new
                        {
                            Id = 8,
                            VersionNumber = "2.4"
                        },
                        new
                        {
                            Id = 9,
                            VersionNumber = "3.1"
                        },
                        new
                        {
                            Id = 10,
                            VersionNumber = "3.2"
                        },
                        new
                        {
                            Id = 11,
                            VersionNumber = "3.3"
                        },
                        new
                        {
                            Id = 12,
                            VersionNumber = "3.4"
                        });
                });

            modelBuilder.Entity("web_platform.Models.SecurityIssuePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CMSComponentVersionId")
                        .HasColumnType("int");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueReproduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CMSComponentVersionId");

                    b.ToTable("SecurityIssuePosts");
                });

            modelBuilder.Entity("web_platform.Models.CMSComponentVersion", b =>
                {
                    b.HasOne("web_platform.Models.CMSComponent", "CMSComponent")
                        .WithMany("CMSComponentVersions")
                        .HasForeignKey("CMSComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_platform.Models.ComponentVersion", "Version")
                        .WithMany("CMSComponentVersions")
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CMSComponent");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("web_platform.Models.SecurityIssuePost", b =>
                {
                    b.HasOne("web_platform.Models.CMSComponentVersion", "CMSComponentVersion")
                        .WithMany()
                        .HasForeignKey("CMSComponentVersionId");

                    b.Navigation("CMSComponentVersion");
                });

            modelBuilder.Entity("web_platform.Models.CMSComponent", b =>
                {
                    b.Navigation("CMSComponentVersions");
                });

            modelBuilder.Entity("web_platform.Models.ComponentVersion", b =>
                {
                    b.Navigation("CMSComponentVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
